name: CI/CD Despliegue

on:
  push:
    branches: [ "main" ] #quiero que se ejecute al subir a main

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 'uses' debe ir DENTRO del paso 'name'
      - name: checkout del codigo
        uses: actions/checkout@v4

      # Este estaba bien
      - name: configurar node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # 'run' debe ir DENTRO del paso 'name'
      - name: instalar npm
        run: npm install

      # Este estaba bien
      - name: ejecutar pruebas unitarias
        run: npm test

      # Este estaba bien
      - name: Generar la documentación con jsdoc
        run: npm run docs

      # Este estaba bien
      - name: Vercel Action
        # You may pin to the exact commit or the version.
        uses: amondnet/vercel-action@v25
        with:
          # Vercel token
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #despliega solo la carpeta docs
          working-directory: ./docs
          #despliega a produccion
          vercel-args: '--prod'
        
